### ISSUE TITLE
Video is not playing on MAC / Safari

### ISSUE THREAD

**Issue by jackleblack-kpt** [BlackrockDigital/startbootstrap-coming-soon#13]
Add to bottom of index.html
```
<script>
    $(document).ready(function() {
        //FORCE VIDEO PLAY - SAFARI 11 ISSUE
            $('body').data('vide').getVideoObject().play();
    });
</script>
```

It seems to be Apple's new video playback policy! https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/

**Comment by davidtmiller** [comment]
Removed Vide plugin in #15 and now use HTML5 video elements so this should work now.
