### ISSUE TITLE
Moto G 4 broken layout

### ISSUE THREAD

**Issue by erikcunha** [BlackrockDigital/startbootstrap-coming-soon#4]
Hi, when i visit the site from my device it seems to be broken: 
![bloggif_5a5abae8b6bd8](https://user-images.githubusercontent.com/27955793/34912093-c28a9bda-f8be-11e7-93f5-c12292fc32d8.png)

Any way to fix it ?

**Comment by greatpython** [comment]
@erikcunha  Can you please let know what you was expecting? When I tested with same device it is working smooth.

**Comment by erikcunha** [comment]
I guess it was fixed already but the white bar on the bottom, it shouldn't be there.
