### ISSUE TITLE
Issues pushing to Netlify.com build error - code works locally

### ISSUE THREAD

**Issue by IBLoud** [BlackrockDigital/startbootstrap-coming-soon#8]
Error
1:55:24 PM: Build complete: exit code: 1
1:55:24 PM: Error running command: Build script returned non-zero exit code: 1
1:55:24 PM: Failing build: Failed to build site

Answer from support:
there is no build  task within your gulpfile.js. When you mention it works locally, you probably run the command gulp dev  which is mentioned on your repo's README.md file. However do note that the build command you are using is gulp build which is, as I mentioned, not defined in your gulpfile.js.

The only tasks mentioned are:

gulp  the default task that builds everything
gulp dev  browserSync opens the project in your default browser and live reloads when changes are made
gulp sass  compiles SCSS files into CSS
gulp minify-css  minifies the compiled CSS file
gulp minify-js  minifies the themes JS file
gulp copy  copies dependencies from node_modules to the vendor directory
This is basically the gist of what my initial response was and that you should take a look at your gulpfile as a first step.

In any case, the reason your deploy fails is because you are using an non-existent task as your build command. Reading through the gulpfile.js  on your repo, I do see that the default task is what you'll want. That said, you'll want to use gulp  as your build command, which implies the default task.

FYI: the task gulp copy is actually gulp vendor if you go by the actual gulpfile.js which looks to be like a typo.

**Comment by davidtmiller** [comment]
Yes I'll need to update the docs to reflect the changes in gulp commands. There is no `gulp build` task though, instead I just use the default task `gulp` to build everything.
