### ISSUE TITLE
gulp commands wrong

### ISSUE THREAD

**Issue by FelixButzbach** [BlackrockDigital/startbootstrap-coming-soon#9]
Hei there.
First of all, thanks for this template, it works pretty well.

Just the following gulp commands (given in the readme) are not working.
gulp sass
gulp minify-css
gulp minify-js
gulp copy

They should be:
gulp css
gulp js
gulp vendor

**Comment by RaulS11** [comment]
Also, I ran:
`npm-install`
and after:
`gulp dev`,
I encountered: "No command 'gulp' found"
According to this post: https://stackoverflow.com/questions/22224831/no-command-gulp-found-after-installation
I had to run `sudo npm install --global gulp-cli` and it works like a charm.

**Comment by davidtmiller** [comment]
I'll need to update this in the docs. `gulp dev` is still correct though.

**Comment by davidtmiller** [comment]
Fixed in f6b169df829b03b960eb2a108af5c33048abb9f2
